// <auto-generated/>
#pragma warning disable CS0618
using FuelWebUi.ApiClient.Api.StaffMembers.Item;
using FuelWebUi.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace FuelWebUi.ApiClient.Api.StaffMembers
{
    /// <summary>
    /// Builds and executes requests for operations under \api\StaffMembers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StaffMembersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the FuelWebUi.ApiClient.api.StaffMembers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Api.StaffMembers.Item.StaffMembersItemRequestBuilder"/></returns>
        public global::FuelWebUi.ApiClient.Api.StaffMembers.Item.StaffMembersItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::FuelWebUi.ApiClient.Api.StaffMembers.Item.StaffMembersItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the FuelWebUi.ApiClient.api.StaffMembers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Api.StaffMembers.Item.StaffMembersItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::FuelWebUi.ApiClient.Api.StaffMembers.Item.StaffMembersItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::FuelWebUi.ApiClient.Api.StaffMembers.Item.StaffMembersItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StaffMembersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/StaffMembers{?page*,pageSize*,sortBy*,sortDir*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StaffMembersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/StaffMembers{?page*,pageSize*,sortBy*,sortDir*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves all staff members with pagination.
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Models.StaffMemberListDtoPagedResultDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::FuelWebUi.ApiClient.Models.StaffMemberListDtoPagedResultDto?> GetAsync(Action<RequestConfiguration<global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder.StaffMembersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::FuelWebUi.ApiClient.Models.StaffMemberListDtoPagedResultDto> GetAsync(Action<RequestConfiguration<global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder.StaffMembersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::FuelWebUi.ApiClient.Models.StaffMemberListDtoPagedResultDto>(requestInfo, global::FuelWebUi.ApiClient.Models.StaffMemberListDtoPagedResultDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new staff member.
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Models.StaffMember"/></returns>
        /// <param name="body">Represents a staff member (coach, manager, or assistant) in the sports management system.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::FuelWebUi.ApiClient.Models.StaffMember?> PostAsync(global::FuelWebUi.ApiClient.Models.StaffMember body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::FuelWebUi.ApiClient.Models.StaffMember> PostAsync(global::FuelWebUi.ApiClient.Models.StaffMember body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::FuelWebUi.ApiClient.Models.StaffMember>(requestInfo, global::FuelWebUi.ApiClient.Models.StaffMember.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves all staff members with pagination.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder.StaffMembersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder.StaffMembersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new staff member.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Represents a staff member (coach, manager, or assistant) in the sports management system.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::FuelWebUi.ApiClient.Models.StaffMember body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::FuelWebUi.ApiClient.Models.StaffMember body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves all staff members with pagination.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StaffMembersRequestBuilderGetQueryParameters 
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortBy")]
            public string? SortBy { get; set; }
#nullable restore
#else
            [QueryParameter("sortBy")]
            public string SortBy { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortDir")]
            public string? SortDir { get; set; }
#nullable restore
#else
            [QueryParameter("sortDir")]
            public string SortDir { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StaffMembersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder.StaffMembersRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StaffMembersRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
