// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace FuelWebUi.ApiClient.Models
{
    /// <summary>
    /// Lightweight evaluation row returned by list endpoints.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EvaluationListDto : IParsable
    {
        /// <summary>The date property</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>The evaluationId property</summary>
        public int? EvaluationId { get; set; }
        /// <summary>The playerId property</summary>
        public int? PlayerId { get; set; }
        /// <summary>The playerName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlayerName { get; set; }
#nullable restore
#else
        public string PlayerName { get; set; }
#endif
        /// <summary>The staffMemberId property</summary>
        public int? StaffMemberId { get; set; }
        /// <summary>The staffMemberName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StaffMemberName { get; set; }
#nullable restore
#else
        public string StaffMemberName { get; set; }
#endif
        /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Models.EvaluationListDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::FuelWebUi.ApiClient.Models.EvaluationListDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::FuelWebUi.ApiClient.Models.EvaluationListDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "evaluationId", n => { EvaluationId = n.GetIntValue(); } },
                { "playerId", n => { PlayerId = n.GetIntValue(); } },
                { "playerName", n => { PlayerName = n.GetStringValue(); } },
                { "staffMemberId", n => { StaffMemberId = n.GetIntValue(); } },
                { "staffMemberName", n => { StaffMemberName = n.GetStringValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteIntValue("evaluationId", EvaluationId);
            writer.WriteIntValue("playerId", PlayerId);
            writer.WriteStringValue("playerName", PlayerName);
            writer.WriteIntValue("staffMemberId", StaffMemberId);
            writer.WriteStringValue("staffMemberName", StaffMemberName);
            writer.WriteStringValue("summary", Summary);
        }
    }
}
#pragma warning restore CS0618
