// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace FuelWebUi.ApiClient.Models
{
    /// <summary>
    /// Represents a player in the sports management system.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Player : IParsable
    {
        /// <summary>Gets or sets the association identifier for the player.</summary>
        public int? AssociationID { get; set; }
        /// <summary>Gets or sets the player&apos;s birth date.</summary>
        public DateTimeOffset? BirthDate { get; set; }
        /// <summary>Gets or sets the player&apos;s email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Gets or sets the list of evaluations associated with the player.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::FuelWebUi.ApiClient.Models.Evaluation>? Evaluations { get; set; }
#nullable restore
#else
        public List<global::FuelWebUi.ApiClient.Models.Evaluation> Evaluations { get; set; }
#endif
        /// <summary>Gets or sets the player&apos;s first name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>Gets or sets the player&apos;s jersey number.</summary>
        public int? JerseyNumber { get; set; }
        /// <summary>Gets or sets the player&apos;s last name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Gets or sets the unique identifier for the player.</summary>
        public int? PlayerID { get; set; }
        /// <summary>Represents the position of the player.</summary>
        public global::FuelWebUi.ApiClient.Models.Position? Position { get; set; }
        /// <summary>Gets or sets the team identifier for the player.</summary>
        public int? TeamID { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Models.Player"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::FuelWebUi.ApiClient.Models.Player CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::FuelWebUi.ApiClient.Models.Player();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "associationID", n => { AssociationID = n.GetIntValue(); } },
                { "birthDate", n => { BirthDate = n.GetDateTimeOffsetValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "evaluations", n => { Evaluations = n.GetCollectionOfObjectValues<global::FuelWebUi.ApiClient.Models.Evaluation>(global::FuelWebUi.ApiClient.Models.Evaluation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "jerseyNumber", n => { JerseyNumber = n.GetIntValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "playerID", n => { PlayerID = n.GetIntValue(); } },
                { "position", n => { Position = n.GetEnumValue<global::FuelWebUi.ApiClient.Models.Position>(); } },
                { "teamID", n => { TeamID = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("associationID", AssociationID);
            writer.WriteDateTimeOffsetValue("birthDate", BirthDate);
            writer.WriteStringValue("email", Email);
            writer.WriteCollectionOfObjectValues<global::FuelWebUi.ApiClient.Models.Evaluation>("evaluations", Evaluations);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteIntValue("jerseyNumber", JerseyNumber);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteIntValue("playerID", PlayerID);
            writer.WriteEnumValue<global::FuelWebUi.ApiClient.Models.Position>("position", Position);
            writer.WriteIntValue("teamID", TeamID);
        }
    }
}
#pragma warning restore CS0618
