// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace FuelWebUi.ApiClient.Models
{
    /// <summary>
    /// Lightweight player row returned by list endpoints.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlayerListDto : IParsable
    {
        /// <summary>The associationId property</summary>
        public int? AssociationId { get; set; }
        /// <summary>The associationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssociationName { get; set; }
#nullable restore
#else
        public string AssociationName { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The jerseyNumber property</summary>
        public int? JerseyNumber { get; set; }
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The playerId property</summary>
        public int? PlayerId { get; set; }
        /// <summary>The position property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Position { get; set; }
#nullable restore
#else
        public string Position { get; set; }
#endif
        /// <summary>The teamId property</summary>
        public int? TeamId { get; set; }
        /// <summary>The teamName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamName { get; set; }
#nullable restore
#else
        public string TeamName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Models.PlayerListDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::FuelWebUi.ApiClient.Models.PlayerListDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::FuelWebUi.ApiClient.Models.PlayerListDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "associationId", n => { AssociationId = n.GetIntValue(); } },
                { "associationName", n => { AssociationName = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "jerseyNumber", n => { JerseyNumber = n.GetIntValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "playerId", n => { PlayerId = n.GetIntValue(); } },
                { "position", n => { Position = n.GetStringValue(); } },
                { "teamId", n => { TeamId = n.GetIntValue(); } },
                { "teamName", n => { TeamName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("associationId", AssociationId);
            writer.WriteStringValue("associationName", AssociationName);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteIntValue("jerseyNumber", JerseyNumber);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteIntValue("playerId", PlayerId);
            writer.WriteStringValue("position", Position);
            writer.WriteIntValue("teamId", TeamId);
            writer.WriteStringValue("teamName", TeamName);
        }
    }
}
#pragma warning restore CS0618
