// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace FuelWebUi.ApiClient.Models
{
    /// <summary>Represents the position of the player.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Position
    {
        [EnumMember(Value = "C")]
        #pragma warning disable CS1591
        C,
        #pragma warning restore CS1591
        [EnumMember(Value = "LW")]
        #pragma warning disable CS1591
        LW,
        #pragma warning restore CS1591
        [EnumMember(Value = "RW")]
        #pragma warning disable CS1591
        RW,
        #pragma warning restore CS1591
        [EnumMember(Value = "D")]
        #pragma warning disable CS1591
        D,
        #pragma warning restore CS1591
        [EnumMember(Value = "G")]
        #pragma warning disable CS1591
        G,
        #pragma warning restore CS1591
    }
}
