// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace FuelWebUi.ApiClient.Models
{
    /// <summary>Represents the role a staff member holds.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StaffRole
    {
        [EnumMember(Value = "Coach")]
        #pragma warning disable CS1591
        Coach,
        #pragma warning restore CS1591
        [EnumMember(Value = "Manager")]
        #pragma warning disable CS1591
        Manager,
        #pragma warning restore CS1591
        [EnumMember(Value = "Assistant")]
        #pragma warning disable CS1591
        Assistant,
        #pragma warning restore CS1591
        [EnumMember(Value = "Evaluator")]
        #pragma warning disable CS1591
        Evaluator,
        #pragma warning restore CS1591
    }
}
