// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace FuelWebUi.ApiClient.Models
{
    /// <summary>
    /// Represents a staff member (coach, manager, or assistant) in the sports management system.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StaffMember : IParsable
    {
        /// <summary>Gets or sets the staff member&apos;s email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Gets or sets the staff member&apos;s first name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>Gets or sets the staff member&apos;s last name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Represents the role a staff member holds.</summary>
        public global::FuelWebUi.ApiClient.Models.StaffRole? Role { get; set; }
        /// <summary>Gets or sets the unique identifier for the staff member.</summary>
        public int? StaffMemberID { get; set; }
        /// <summary>Gets or sets the team identifier for the staff member.</summary>
        public int? TeamID { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Models.StaffMember"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::FuelWebUi.ApiClient.Models.StaffMember CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::FuelWebUi.ApiClient.Models.StaffMember();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::FuelWebUi.ApiClient.Models.StaffRole>(); } },
                { "staffMemberID", n => { StaffMemberID = n.GetIntValue(); } },
                { "teamID", n => { TeamID = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteEnumValue<global::FuelWebUi.ApiClient.Models.StaffRole>("role", Role);
            writer.WriteIntValue("staffMemberID", StaffMemberID);
            writer.WriteIntValue("teamID", TeamID);
        }
    }
}
#pragma warning restore CS0618
