// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace FuelWebUi.ApiClient.Models
{
    /// <summary>
    /// Lightweight team row returned by list endpoints.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TeamListDto : IParsable
    {
        /// <summary>The associationId property</summary>
        public int? AssociationId { get; set; }
        /// <summary>The associationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssociationName { get; set; }
#nullable restore
#else
        public string AssociationName { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The playerCount property</summary>
        public int? PlayerCount { get; set; }
        /// <summary>The teamId property</summary>
        public int? TeamId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Models.TeamListDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::FuelWebUi.ApiClient.Models.TeamListDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::FuelWebUi.ApiClient.Models.TeamListDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "associationId", n => { AssociationId = n.GetIntValue(); } },
                { "associationName", n => { AssociationName = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "playerCount", n => { PlayerCount = n.GetIntValue(); } },
                { "teamId", n => { TeamId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("associationId", AssociationId);
            writer.WriteStringValue("associationName", AssociationName);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("playerCount", PlayerCount);
            writer.WriteIntValue("teamId", TeamId);
        }
    }
}
#pragma warning restore CS0618
