// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace FuelWebUi.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Team : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Gets or sets the association identifier for the team.</summary>
        public int? AssociationID { get; set; }
        /// <summary>Gets or sets the name of the team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the list of players assigned to the team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::FuelWebUi.ApiClient.Models.Player>? Players { get; set; }
#nullable restore
#else
        public List<global::FuelWebUi.ApiClient.Models.Player> Players { get; set; }
#endif
        /// <summary>Gets or sets the unique identifier for the team.</summary>
        public int? TeamID { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::FuelWebUi.ApiClient.Models.Team"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::FuelWebUi.ApiClient.Models.Team CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::FuelWebUi.ApiClient.Models.Team();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "associationID", n => { AssociationID = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "players", n => { Players = n.GetCollectionOfObjectValues<global::FuelWebUi.ApiClient.Models.Player>(global::FuelWebUi.ApiClient.Models.Player.CreateFromDiscriminatorValue)?.AsList(); } },
                { "teamID", n => { TeamID = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("associationID", AssociationID);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::FuelWebUi.ApiClient.Models.Player>("players", Players);
            writer.WriteIntValue("teamID", TeamID);
        }
    }
}
#pragma warning restore CS0618
