// <auto-generated/>
#pragma warning disable CS0618
using FuelWebUi.ApiClient.Api.Associations;
using FuelWebUi.ApiClient.Api.Evaluations;
using FuelWebUi.ApiClient.Api.Players;
using FuelWebUi.ApiClient.Api.StaffMembers;
using FuelWebUi.ApiClient.Api.Teams;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace FuelWebUi.ApiClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Associations property</summary>
        public global::FuelWebUi.ApiClient.Api.Associations.AssociationsRequestBuilder Associations
        {
            get => new global::FuelWebUi.ApiClient.Api.Associations.AssociationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Evaluations property</summary>
        public global::FuelWebUi.ApiClient.Api.Evaluations.EvaluationsRequestBuilder Evaluations
        {
            get => new global::FuelWebUi.ApiClient.Api.Evaluations.EvaluationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Players property</summary>
        public global::FuelWebUi.ApiClient.Api.Players.PlayersRequestBuilder Players
        {
            get => new global::FuelWebUi.ApiClient.Api.Players.PlayersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The StaffMembers property</summary>
        public global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder StaffMembers
        {
            get => new global::FuelWebUi.ApiClient.Api.StaffMembers.StaffMembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Teams property</summary>
        public global::FuelWebUi.ApiClient.Api.Teams.TeamsRequestBuilder Teams
        {
            get => new global::FuelWebUi.ApiClient.Api.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::FuelWebUi.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::FuelWebUi.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
