// <auto-generated />
using System;
using FuelApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelApp.Migrations
{
    [DbContext(typeof(FuelAppContext))]
    partial class FuelAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuelApp.Models.Association", b =>
                {
                    b.Property<int>("AssociationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssociationID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssociationID");

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("FuelApp.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("EvaluationId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_Evaluation_PlayerId");

                    b.HasIndex("StaffMemberId")
                        .HasDatabaseName("IX_Evaluation_StaffMemberId");

                    b.HasIndex("Date", "EvaluationId")
                        .IsDescending()
                        .HasDatabaseName("IX_Evaluation_Date_EvaluationId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("FuelApp.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<int?>("AssociationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("AssociationID")
                        .HasDatabaseName("IX_Player_AssociationID");

                    b.HasIndex("TeamID")
                        .HasDatabaseName("IX_Player_TeamID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FuelApp.Models.StaffMember", b =>
                {
                    b.Property<int>("StaffMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffMemberID"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("StaffMemberID");

                    b.HasIndex("TeamID")
                        .HasDatabaseName("IX_StaffMember_TeamID");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("FuelApp.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<int?>("AssociationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeamID");

                    b.HasIndex("AssociationID")
                        .HasDatabaseName("IX_Team_AssociationID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FuelApp.Models.Evaluation", b =>
                {
                    b.HasOne("FuelApp.Models.Player", "Player")
                        .WithMany("Evaluations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelApp.Models.StaffMember", "StaffMember")
                        .WithMany("Evaluations")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("FuelApp.Models.Player", b =>
                {
                    b.HasOne("FuelApp.Models.Association", "Association")
                        .WithMany()
                        .HasForeignKey("AssociationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FuelApp.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Association");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FuelApp.Models.StaffMember", b =>
                {
                    b.HasOne("FuelApp.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FuelApp.Models.Team", b =>
                {
                    b.HasOne("FuelApp.Models.Association", "Association")
                        .WithMany("Teams")
                        .HasForeignKey("AssociationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Association");
                });

            modelBuilder.Entity("FuelApp.Models.Association", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FuelApp.Models.Player", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("FuelApp.Models.StaffMember", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("FuelApp.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
